# Generated by Django 5.2 on 2025-04-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genres',
            new_name='Genre',
        ),
    ]
